name: Gatus Monitoring

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  gatus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gatus
        uses: twin/gatus-action@v1
        with:
          config-file: gatus.yaml
        env:
          GATUS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
